// Code generated by protoc-gen-go. DO NOT EDIT.
// source: diadust.proto

package diadust

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Image struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	OriginalName         string   `protobuf:"bytes,3,opt,name=original_name,json=originalName" json:"original_name,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Tags                 []int32  `protobuf:"varint,5,rep,packed,name=tags" json:"tags,omitempty"`
	Created              int32    `protobuf:"varint,6,opt,name=created" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_diadust_bc098185a0cb7a96, []int{0}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Image) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Image) GetOriginalName() string {
	if m != nil {
		return m.OriginalName
	}
	return ""
}

func (m *Image) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Image) GetTags() []int32 {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Image) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ImageHash struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageHash) Reset()         { *m = ImageHash{} }
func (m *ImageHash) String() string { return proto.CompactTextString(m) }
func (*ImageHash) ProtoMessage()    {}
func (*ImageHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_diadust_bc098185a0cb7a96, []int{1}
}
func (m *ImageHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageHash.Unmarshal(m, b)
}
func (m *ImageHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageHash.Marshal(b, m, deterministic)
}
func (dst *ImageHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageHash.Merge(dst, src)
}
func (m *ImageHash) XXX_Size() int {
	return xxx_messageInfo_ImageHash.Size(m)
}
func (m *ImageHash) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageHash.DiscardUnknown(m)
}

var xxx_messageInfo_ImageHash proto.InternalMessageInfo

func (m *ImageHash) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ImageHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Tag struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_diadust_bc098185a0cb7a96, []int{2}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Image)(nil), "diadust.Image")
	proto.RegisterType((*ImageHash)(nil), "diadust.ImageHash")
	proto.RegisterType((*Tag)(nil), "diadust.Tag")
}

func init() { proto.RegisterFile("diadust.proto", fileDescriptor_diadust_bc098185a0cb7a96) }

var fileDescriptor_diadust_bc098185a0cb7a96 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x8e, 0x83, 0x30,
	0x10, 0x85, 0x65, 0xc0, 0x20, 0x46, 0xcb, 0x16, 0xae, 0x5c, 0x22, 0xb6, 0x61, 0x9b, 0xa4, 0xc8,
	0x25, 0x92, 0x26, 0x05, 0x4a, 0x1f, 0x4d, 0x62, 0xcb, 0xb6, 0x14, 0x7e, 0x84, 0xcd, 0x45, 0x72,
	0xe2, 0xc8, 0x13, 0xe8, 0xe8, 0xbe, 0x19, 0xbf, 0x27, 0x7f, 0x1a, 0xa8, 0x94, 0x43, 0xb5, 0xf8,
	0x70, 0x98, 0xe6, 0x31, 0x8c, 0xa2, 0x58, 0xc7, 0xe6, 0xcd, 0x80, 0x5f, 0x7a, 0x34, 0x5a, 0xfc,
	0x42, 0xe2, 0x94, 0x64, 0x35, 0x6b, 0x79, 0x97, 0x38, 0x25, 0x04, 0x64, 0xcb, 0xe2, 0x94, 0x4c,
	0x6a, 0xd6, 0x96, 0x1d, 0xb1, 0xf8, 0x83, 0x6a, 0x9c, 0x9d, 0x71, 0x03, 0xbe, 0xee, 0x03, 0xf6,
	0x5a, 0xa6, 0xf4, 0xf8, 0xb3, 0x2d, 0xaf, 0xd8, 0xeb, 0x58, 0x9c, 0x30, 0x58, 0x99, 0x7d, 0x8b,
	0x91, 0xe3, 0x2e, 0xa0, 0xf1, 0x92, 0xd7, 0x69, 0xcb, 0x3b, 0x62, 0x21, 0xa1, 0x78, 0xce, 0x1a,
	0x83, 0x56, 0x32, 0xa7, 0x5f, 0xb7, 0xb1, 0x39, 0x42, 0x49, 0x4e, 0x67, 0xf4, 0x76, 0xcf, 0xcb,
	0xa2, 0xb7, 0x9b, 0x57, 0xe4, 0xe6, 0x1f, 0xd2, 0x1b, 0x9a, 0xbd, 0x28, 0x59, 0xae, 0xd1, 0xc8,
	0x8f, 0x9c, 0x0e, 0x70, 0xfa, 0x04, 0x00, 0x00, 0xff, 0xff, 0xca, 0x39, 0x09, 0xac, 0x11, 0x01,
	0x00, 0x00,
}
